kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:18
  commands:
  - yarn
  - yarn build

- name: publish
  image: plugins/netlify
  settings:
    path: ./build
    prod: true
    site: 2dc01b76-a219-41c6-8333-d2a7067c34d9
    token:
      from_secret: token
  when:
    event:
    - push
    branch:
    - main

trigger:
  event:
  - push
  - pull_request
