## it inject the chaos for the ingrees and egress traffic for specific ips/hosts
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  chaosServiceAccount: litmus-admin
  experiments:
  - name: ec2-network-loss
    spec:
      components:
        env:
        # name of the network interface 
        - name: NETWORK_INTERFACE
          value: 'eth0'

        - name: EC2_INSTANCE_ID
          value: 'instance-1'

        - name: REGION
          value: '<region for EC2_INSTANCE_ID>'