# process ids of target processes
apiVersion: litmuchaos.io/v1alpha1
kind: LinuxFault
metadata:
  name: linux-cpu-stress
  labels:
    name: cpu-stress
spec:
  processKillChaos/inputs:
    processIDs: "13453,32444,27436"
    duration: 30