# defines pod image and label selectors
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  chaosServiceAccount: litmus-admin
  experiments:
  - name: kubelet-density
    spec:
      components:
        env:
        # image of the pod
        - name: POD_IMAGE
          value: '<pod-image>'
        # pod label selectors
        - name: POD_SELECTOR
          value: '<label-selectors>'
        - name: TARGET_NODE
          value: 'node1'